# Interactive .env.local writer (values are not echoed).
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$dest = Join-Path $root '.env.local'

if (Test-Path $dest) {
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $backup = "$dest.backup-$stamp"
  Copy-Item -Path $dest -Destination $backup -Force
  Write-Host "Backed up existing .env.local -> $backup"
}

function Read-Secret([string]$label) {
  $secure = Read-Host "$label" -AsSecureString
  $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  try {
    return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
  } finally {
    [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
  }
}

Write-Host "Tactical HUD - enter keys (required)."
Write-Host ""

$url = (Read-Host 'VITE_SUPABASE_URL (https://xxx.supabase.co)').Trim()
$anon = Read-Secret 'VITE_SUPABASE_ANON_KEY (sb_publishable_...)'
$sign = Read-Secret 'VITE_RESCUE_SIGNING_KEY (same as Supabase secret RESCUE_SIGNING_KEY)'
$defaultRescue = if ($url) { "$($url.TrimEnd('/'))/functions/v1/send-rescue-email" } else { '' }
$rescuePrompt = "VITE_RESCUE_EMAIL_URL [$defaultRescue]"
$rescue = (Read-Host $rescuePrompt).Trim()
if (-not $rescue -and $defaultRescue) { $rescue = $defaultRescue }

$lines = @(
  '# Tactical HUD - generated by scripts/set-env-interactive.ps1',
  "# $(Get-Date -Format o)",
  '',
  "VITE_SUPABASE_URL=$url",
  "VITE_SUPABASE_ANON_KEY=$anon",
  "VITE_RESCUE_SIGNING_KEY=$sign",
  "VITE_RESCUE_EMAIL_URL=$rescue",
  ''
)

$lines | Set-Content -Path $dest -Encoding utf8
Write-Host ""
Write-Host "Wrote .env.local"
Write-Host "Run: npm run env:check"
Write-Host "Then: npm run dev"
